### PR TITLE
refactor: remove old v2 requirements

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
this will fail CI until https://github.com/jenkins-x/jx-pipeline/pull/132 is merged 

let's plan release with other repos
/hold

**Comment by vbehar** [comment]
@rawlingsj will this break compatibility with jx v2?

**Comment by vbehar** [comment]
answering myself after testing: it's still working against a v2 cluster

**Comment by rawlingsj** [comment]
@vbehar yeah the first change we did, did break backwards compatibility and we noticed with pipeline visualizer in mind.  So we reverted that original change and only bumped the v4 for the new requirements API. 

At some point we could add a preview environment for this repo to test changes out ala jx style.

**Comment by vbehar** [comment]
great, thanks for the backward compatibility!
yes, a preview env would be awesome

**Pull request merged**
